version: "3.9"
services:
  api:
    build: ./api
    user: "${UID:?Set UID env variable to your user id}"

  solid:
    build:
      context: ./solid/

  caddy:
    image: caddy:2.6-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

volumes:
  caddy_data:
  caddy_config:
