apiVersion: v1
kind: Service
metadata:
  name: {{ include "alldeals.fullname" . }}-api
  labels:
    {{- include "alldeals.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alldeals.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
